### ISSUE TITLE
First keystroke is ignored when editing increment

### ISSUE THREAD

**Issue by AnonymousPrayers** [F3XTeam/ROBLOX-Building-Tools#11]
When the increment field is selected, the first keystroke entered is ignored, and instead acts as it normally does. For example, pressing 1 as the first keystroke when entering the increment results in tool 1 being selected instead. If "." is the first keystroke being entered, it turns the camera view rather than entering it.

**Comment by GigsD4X** [comment]
Fixed on ROBLOX end
