### ISSUE TITLE
Add all possible colors to the color tool's palette

### ISSUE THREAD

**Issue by GigsD4X** [F3XTeam/ROBLOX-Building-Tools#28]

**Comment by Joyesh** [comment]
I have full code for -almost- the whole color palette in new ROBLOX and good news, it's in hexagon-like form! If you want it, I can give you a hastebin link and you can improve it all you want.
(by the way, my name on roblox is **funzrey**)

**Comment by ThatChristianGuy** [comment]
That's awesome! Could you post that link? Please and thanks!

**Comment by GigsD4X** [comment]
This is actually in BT 2 already, forgot to mark it off!
