### ISSUE TITLE
Add new surface lights

### ISSUE THREAD

**Issue by GigsD4X** [F3XTeam/ROBLOX-Building-Tools#60]

**Comment by AnonymousPrayers** [comment]
Shouldn't this be two separate issues?

**Comment by GigsD4X** [comment]
Yep

**Comment by ThatChristianGuy** [comment]
I think I could do this. Shouldn't be much harder than copy-pasting the SpotLight GUI, adding a new option, and modifying the code some.

**Comment by dhdguysg** [comment]
True TCG, Kind of like when I made my mod for F3X and just duplicated the Material code to add neon
(p.s. i'm funzrey)

**Comment by ThatChristianGuy** [comment]
Neon has been out for a while as an optional update (which I made as you said btw), and this would be a bit more complicated but same concept. (Btw I'm ThatChristianGuy, I have three accounts on here)





On Sun, Sep 27, 2015 at 11:52 AM -0700, "dhdguysg" <notifications@github.com> wrote:












True TCG, Kind of like when I made my mod for F3X and just duplicated the Material code to add neon

(p.s. i'm funzrey)

**Comment by GigsD4X** [comment]
Added in BT 2
