### ISSUE TITLE
Can't stop dragging after ending focus of any textbox?

### ISSUE THREAD

**Issue by NNickey** [F3XTeam/ROBLOX-Building-Tools#68]
When you go ahead and click on a textbox.
For example, the increment of the move tool.
Right after hitting enter, the window would keep the click down request and ignore that you had clicked on a textbox, and drag with the cursor.

**Comment by NNickey** [comment]
A temporary workaround can be to make only the title of each window draggable, instead of the entire eframe.

**Comment by GigsD4X** [comment]
Apparently that doesn't work, since the Draggable property has to be enabled on the frame that is going to be moved. What _would_ work would be what we do with all other inputs, which is overlay a button over the input and manually call :CaptureFocus().

**Comment by NNickey** [comment]
This appears to be fixed by Roblox now.
