### ISSUE TITLE
Auto-update plugin

### ISSUE THREAD

**Issue by AnonymousPrayers** [F3XTeam/ROBLOX-Building-Tools#74]
Would it be possible to automatically update the plugin? script.Source is accessible from plugins, so if HttpService is enabled, it could be fetched from somewhere. If not, the code is just stored locally like normal. Possibly even from here: https://developer.github.com/v3/. If I figure out how the API works, I might try a pull request, but only if you'd think the idea is decent.

**Comment by GigsD4X** [comment]
Possibly with the DataModel:Load() function, I'll check :p

**Comment by AnonymousPrayers** [comment]
Oh, that's right, HttpService doesn't work in studio. (facepalms)

**Comment by GigsD4X** [comment]
It does! It's just that we need a way of loading the .rbxm files in the
build folder from GitHub, not just the scripts :P

**Comment by AnonymousPrayers** [comment]
Okay. I'll ask around a bit and see what I can find.





On Thu, Jul 9, 2015 at 12:17 PM -0700, "Robert" <notifications@github.com> wrote:
It does! It's just that we need a way of loading the .rbxm files in the
build folder from GitHub, not just the scripts :P

On Thu, Jul 9, 2015, 12:05 PM Zenon <notifications@github.com> wrote:

> Oh, that's right, HttpService doesn't work in studio. (facepalms)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/F3XTeam/ROBLOX-Building-Tools/issues/74#issuecomment-120109945>
> .
>


---

**Comment by AnonymousPrayers** [comment]
http://wiki.roblox.com/index.php?title=API:Class/DataModel/GetObjects ?

**Comment by NNickey** [comment]
GigsD4X I don't see what would be bad with using require(assetid) now?
You can keep the original F3X Source free.

**Comment by ThatChristianGuy** [comment]
We could at least use the modules for in-game. The plugin is a lot easier to update than the tool.

**Comment by ThatChristianGuy** [comment]
Couldn't we create the GUI in the core script?

**Comment by NNickey** [comment]
You're able to put the GUI in the core script. Not Couldn't.
I bet it's easier to be able to see what the gui will look like, than having to run the game every time.

**Comment by NNickey** [comment]
PS. Don't go off topic of the main topic of this issue. @ThatChristianGuy

**Comment by ThatChristianGuy** [comment]
@NNickey I mentioned it because Gigs was talking about needing to get the .rbxm files, which mainly contain the GUI. So on-topic, as just creating the tool things would make it possible to use modules or import the source from github.

**Comment by GigsD4X** [comment]
@ThatChristianGuy Nope, the GUI _used_ to be part of the code in the alpha versions of BT, but as the codebase grew we even had to split all the tools into their own scripts, since there's a script size limit.

**Comment by ThatChristianGuy** [comment]
Wow. I never knew that. 





On Sat, Sep 19, 2015 at 2:01 PM -0700, "Robert" <notifications@github.com> wrote:












@ThatChristianGuy Nope, the GUI used to be part of the code in the alpha versions of BT, but as the codebase grew we even had to split all the tools into their own scripts, since there's a script size limit.
