### ISSUE TITLE
Exporting can take too much CPU time & be timed out by the server if there are enough parts

### ISSUE THREAD

**Issue by NNickey** [F3XTeam/ROBLOX-Building-Tools#76]
Although using the Roblox Server for uploading is good for poor computer speeds, BUT what if a lot of people are using tools and want to be able to upload faster by using their PC power instead to save the load on the Roblox Server.

**Comment by GigsD4X** [comment]
Very good point.

**Comment by GigsD4X** [comment]
Fixed in 2.0.0
