### ISSUE TITLE
Right-click shortcut in Move, Resize, and Rotate to change "Last" picks up camera movement

### ISSUE THREAD

**Issue by ThatChristianGuy** [F3XTeam/ROBLOX-Building-Tools#89]
When you right-click and drag to move the camera, and end with your mouse over a selected part while using Resize or Move/Rotate on Local or Last mode, that part becomes the "Last" in the selection. Should probably add the code from Surface that detects camera movement and prevents the action from occurring if it was camera movement.

**Comment by GigsD4X** [comment]
Fixed in BT 2
